-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) as YEAR, MONTH(SALES_DATE) as MONTH, GENDER as GENDER, COUNT(DISTINCT U.USER_ID) as USERS
FROM (SELECT *
      FROM USER_INFO
      WHERE GENDER IS NOT NULL) as U
    JOIN ONLINE_SALE O ON U.USER_ID = O.USER_ID
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY YEAR, MONTH, GENDER ASC

# SELECT *
# FROM (SELECT *
#       FROM USER_INFO
#       WHERE GENDER IS NOT NULL) as U
#     JOIN ONLINE_SALE O ON U.USER_ID = O.USER_ID
# order by sales_date