-- 코드를 입력하세요
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE FAVORITES IN (SELECT MAX(FAVORITES) as FAVORITES
    FROM REST_INFO 
    GROUP BY FOOD_TYPE)
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC
# SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, RI.FAVORITES
# FROM REST_INFO RI JOIN ( 
#     SELECT MAX(FAVORITES) as FAVORITES
#     FROM REST_INFO 
#     GROUP BY FOOD_TYPE
# ) as NR
#     ON RI.FAVORITES = NR.FAVORITES
