-- 코드를 입력하세요
# SELECT YEAR(SALES_DATE) as YEAR, MONTH(SALES_DATE) as MONTH,
# COUNT(*) as PUCHASED_USERS,
# ROUND((count(DISTINCT OS.USER_ID))/hi, 1) as PUCHASED_RATIO
# FROM (SELECT USER_ID, (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = '2021') as hi
#       FROM USER_INFO
#       WHERE YEAR(JOINED) = '2021'
#       ) as UI
#       JOIN ONLINE_SALE as OS ON UI.USER_ID = OS.USER_ID
#     GROUP BY YEAR, MONTH
# ORDER BY YEAR, MONTH

WITH TMP AS (
    SELECT *
    FROM USER_INFO
    WHERE EXTRACT(YEAR FROM JOINED) = 2021
)
SELECT EXTRACT(YEAR FROM SALES_DATE) YEAR, 
       EXTRACT(MONTH FROM SALES_DATE) MONTH,
       COUNT(DISTINCT USER_ID) AS PUCHASED_USERS,
       ROUND(COUNT(DISTINCT USER_ID) / (SELECT COUNT(*) FROM TMP), 1) AS RATIO
FROM ONLINE_SALE
    JOIN TMP USING(USER_ID)
GROUP BY EXTRACT(YEAR FROM SALES_DATE), EXTRACT(MONTH FROM SALES_DATE)
ORDER BY 1, 2