-- 코드를 입력하세요
SELECT FIRST_HALF.FLAVOR
FROM (SELECT FLAVOR FROM ICECREAM_INFO WHERE INGREDIENT_TYPE = 'fruit_based')
    as temp 
    JOIN FIRST_HALF ON temp.FLAVOR = FIRST_HALF.FLAVOR
WHERE TOTAL_ORDER >= 3000
ORDER BY TOTAL_ORDER DESC

# SELECT temp.FLAVOR
# FROM (SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF WHERE TOTAL_ORDER > 3000)
#     as temp 
#     JOIN ICECREAM_INFO ON temp.FLAVOR = ICECREAM_INFO.FLAVOR
# WHERE INGREDIENT_TYPE = 'fruit_based'
# ORDER BY TOTAL_ORDER