# -- 코드를 입력하세요
# SELECT CONCAT('/home/grep/src/', UGB.BOARD_ID, '/',FILE_ID,FILE_NAME,FILE_EXT)
#     as FILE_PATH
# FROM USED_GOODS_FILE UGF 
#     JOIN USED_GOODS_BOARD UGB ON 
#     UGB.BOARD_ID = UGF.BOARD_ID
# WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
# ORDER BY FILE_ID DESC

        
SELECT CONCAT('/home/grep/src/', UGB.BOARD_ID, '/',FILE_ID,FILE_NAME,FILE_EXT)
    as FILE_PATH
FROM USED_GOODS_FILE UGF 
    JOIN (
        SELECT VIEWS, BOARD_ID
        FROM USED_GOODS_BOARD
        WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
    ) UGB ON UGF.BOARD_ID = UGB.BOARD_ID
ORDER BY FILE_ID DESC