-- 코드를 입력하세요
SELECT UGU.USER_ID, UGU.NICKNAME,
CONCAT(UGU.CITY, ' ', UGU.STREET_ADDRESS1, ' ', UGU.STREET_ADDRESS2) as 전체주소,
CONCAT(LEFT(TLNO, 3), '-', MID(TLNO, 4, 4), '-', RIGHT(TLNO, 4)) as 전화번호
FROM USED_GOODS_USER UGU
    JOIN USED_GOODS_BOARD UGB ON UGB.WRITER_ID = UGU.USER_ID
GROUP BY UGU.USER_ID
HAVING COUNT(UGU.USER_ID) >= 3
ORDER BY UGU.USER_ID DESC


