# -- 코드를 입력하세요
SELECT FH.FLAVOR
FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) as NEW_ORDER
     FROM JULY
     GROUP BY FLAVOR) as JY
 JOIN FIRST_HALF FH ON FH.FLAVOR = JY.FLAVOR
GROUP BY FH.FLAVOR
ORDER BY FH.TOTAL_ORDER + JY.NEW_ORDER DESC
LIMIT 3

# SELECT FLAVOR, SUM(TOTAL_ORDER) as NEW_ORDER
# FROM JULY
# GROUP BY FLAVOR

# SELECT FLAVOR, TOTAL_ORDER
# FROM JULY
