-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, SUM(PRICE) as TOTAL_SALES
FROM (SELECT * FROM USED_GOODS_BOARD WHERE STATUS = 'DONE') UGB
    JOIN USED_GOODS_USER UGU ON UGB.WRITER_ID = UGU.USER_ID
GROUP BY WRITER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES ASC

# SELECT PRICE, WRITER_ID FROM USED_GOODS_BOARD 
# ORDER BY WRITER_ID