-- 코드를 입력하세요

SELECT FP1.CATEGORY, PRICE, PRODUCT_NAME
    FROM 
        (SELECT CATEGORY, MAX(PRICE) as MAX_PRICE
        FROM FOOD_PRODUCT
        GROUP BY CATEGORY) as FP1
        JOIN FOOD_PRODUCT FP2 ON FP2.PRICE = FP1.MAX_PRICE and FP2.CATEGORY = FP1.CATEGORY
WHERE FP2.CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY CATEGORY
ORDER BY PRICE DESC


