-- 코드를 입력하세요
SELECT A.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE * SALES) as TOTAL_SALES
FROM (SELECT *
     FROM BOOK_SALES
     WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01') as BS
     JOIN BOOK B ON BS.BOOK_ID = B.BOOK_ID
     JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
 GROUP BY CATEGORY, A.AUTHOR_ID
 ORDER BY A.AUTHOR_ID ASC, CATEGORY DESC