-- 코드를 입력하세요
SELECT DISTINCT(P.PRODUCT_CODE), SUM(OS.SALES_AMOUNT) * P.PRICE as SALES
FROM PRODUCT P 
    JOIN OFFLINE_SALE OS ON P.PRODUCT_ID = OS.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, P.PRODUCT_CODE ASC

# SELECT PRODUCT_CODE, OS.SALES_AMOUNT, P.PRICE 
# FROM PRODUCT P 
#     JOIN OFFLINE_SALE OS ON P.PRODUCT_ID = OS.PRODUCT_ID

# LIMIT 10