SELECT HISTORY_ID, 
    round(DAILY_FEE * (DATEDIFF(END_DATE, START_DATE)+1)
    * (case 
    when DATEDIFF(END_DATE, START_DATE)+1 < 7 then 1
    when DATEDIFF(END_DATE, START_DATE)+1 < 30 then 0.95
    when DATEDIFF(END_DATE, START_DATE)+1 < 90 then 0.92
    else 0.85 end)) as "FEE"
FROM (SELECT CAR_ID, DAILY_FEE
      FROM CAR_RENTAL_COMPANY_CAR
      WHERE CAR_TYPE = '트럭') as CC
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CH ON CC.CAR_ID = CH.CAR_ID
ORDER BY FEE DESC, HISTORY_ID DESC
