-- 코드를 입력하세요
SELECT FP.PRODUCT_ID, PRODUCT_NAME, SUM(AMOUNT * PRICE) as TOTAL_SALES
FROM FOOD_PRODUCT FP 
    JOIN
    (SELECT *
     FROM FOOD_ORDER
     WHERE MONTH(PRODUCE_DATE) = 5) as FO
     ON FP.PRODUCT_ID = FO.PRODUCT_ID
GROUP BY FP.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID ASC
# WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2021-05'