-- 코드를 입력하세요
SELECT RR.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, 
    ROUND(AVG(RR.REVIEW_SCORE), 2) as SCORE
FROM REST_REVIEW RR
    JOIN (SELECT * FROM REST_INFO WHERE ADDRESS LIKE '서울%') as RI 
        ON RI.REST_ID = RR.REST_ID
    
GROUP BY RR.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC

# SELECT RR.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, 
#     ROUND(AVG(RR.REVIEW_SCORE), 2) as SCORE
# FROM REST_REVIEW RR
#     JOIN (SELECT * FROM REST_INFO WHERE ADDRESS LIKE '서울특별시%') as RI 
#         ON RI.REST_ID = RR.REST_ID